"""initial schema

Revision ID: bd3022d6257b
Revises: 
Create Date: 2026-02-11 09:58:34.765186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd3022d6257b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_item_cursors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('cursor', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_item_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_provider_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('cursor_before', sa.String(), nullable=True),
    sa.Column('cursor_after', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'endpoint', 'item_id', 'cursor_after', name='uq_raw_provider_event_cursor')
    )
    op.create_index(op.f('ix_raw_provider_events_item_id'), 'raw_provider_events', ['item_id'], unique=False)
    op.create_index(op.f('ix_raw_provider_events_user_id'), 'raw_provider_events', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSITORY', 'CREDIT', 'BROKERAGE', 'INVESTMENT', 'LOAN', 'OTHER', name='account_type'), nullable=False),
    sa.Column('subtype', sa.Enum('CHECKING', 'SAVINGS', 'MONEY_MARKET', 'CASH_MANAGEMENT', 'PREPAID', 'CD', 'EBT', 'HEALTH_SAVINGS', 'CREDIT_CARD', 'AUTO_LOAN', 'STUDENT_LOAN', 'MORTGAGE', 'LINE_OF_CREDIT', 'HOME_EQUITY', 'OVERDRAFT', 'IRA', 'SEP_IRA', 'ROTH_IRA', 'SIMPLE_IRA', '_401K', '_403B', '_457B', '_529', 'OTHER', name='account_subtype'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_import_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('apr', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('category_primary', sa.String(), nullable=True),
    sa.Column('category_detailed', sa.String(), nullable=True),
    sa.Column('category_confidence_level', sa.String(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('iso_currency_code', sa.String(), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_index(op.f('ix_raw_provider_events_user_id'), table_name='raw_provider_events')
    op.drop_index(op.f('ix_raw_provider_events_item_id'), table_name='raw_provider_events')
    op.drop_table('raw_provider_events')
    op.drop_table('bank_item_tokens')
    op.drop_table('bank_item_cursors')
    # ### end Alembic commands ###
