"""initial schema

Revision ID: f955f8f53252
Revises: 
Create Date: 2026-02-02 13:31:32.682592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f955f8f53252'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_item_cursors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('cursor', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bank_item_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('institution_id', sa.String(length=100), nullable=False),
    sa.Column('institution_name', sa.String(length=100), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSITORY', 'CREDIT', 'BROKERAGE', 'INVESTMENT', 'LOAN', 'OTHER', name='account_type'), nullable=False),
    sa.Column('subtype', sa.Enum('CHECKING', 'SAVINGS', 'MONEY_MARKET', 'CASH_MANAGEMENT', 'PREPAID', 'CD', 'EBT', 'HEALTH_SAVINGS', 'CREDIT_CARD', 'AUTO_LOAN', 'STUDENT_LOAN', 'MORTGAGE', 'LINE_OF_CREDIT', 'HOME_EQUITY', 'OVERDRAFT', 'IRA', 'SEP_IRA', 'ROTH_IRA', 'SIMPLE_IRA', '_401K', '_403B', '_457B', '_529', 'OTHER', name='account_subtype'), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_import_completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('category_primary', sa.String(), nullable=True),
    sa.Column('category_detailed', sa.String(), nullable=True),
    sa.Column('category_confidence_level', sa.String(), nullable=True),
    sa.Column('pending', sa.Boolean(), nullable=True),
    sa.Column('iso_currency_code', sa.String(), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_table('users')
    op.drop_table('bank_item_tokens')
    op.drop_table('bank_item_cursors')
    # ### end Alembic commands ###
