name: Backend Jobs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt
          pip install black flake8 pylint
      - run: |
          black --diff src/backend \
          --line-length 88
      - run: | 
          flake8 src/backend \
          --max-line-length 88 \
          --exclude=alembic,pytests,scripts,__init__.py
      - run: |
          pylint src/backend \
            --ignore=alembic,pytests,scripts \
            --disable=too-few-public-methods \
            --max-line-length=88 \
            --ignore-patterns=test_.*\.py,__init__.py


  test:
    name: Run Pytests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r src/backend/requirements.txt pytest
      - run: echo "PYTHONPATH=src/backend" >> $GITHUB_ENV
      - run: echo "DATABASE_URL=sqlite:///test.db" >> $GITHUB_ENV
      - run: |
          coverage run -m pytest --cov=src/backend \
          --cov-report=term-missing --cov-report=xml \
          --cov-report=html --maxfail=1 \
          --disable-warnings -v
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov
